import {useEffect,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {ArrowUpRight,CalendarDays,Check,ChevronLeft,ChevronRight,Plus,Repeat2,Trash2,Upload} from 'lucide-react';
import {supabase} from '../lib/supabase';
import {availabilityMode,opportunityLabel,type OpportunityType} from '../lib/domain';
import {extractBrandPalette} from '../lib/branding';
import {useWorkspace} from './Workspace';

type Day={date:string;startTime:string;endTime:string;location:string};
type Form={name:string;description:string;type:OpportunityType;date:string;endDate:string;startTime:string;endTime:string;location:string;term:string;availability:string;days:Day[];logoUrl:string;primaryColor:string;secondaryColor:string};
const blank:Form={name:'',description:'',type:'one_time',date:'',endDate:'',startTime:'08:00',endTime:'16:00',location:'',term:'',availability:'flexible',days:[],logoUrl:'',primaryColor:'#163a5f',secondaryColor:'#ef7b45'};
const steps=['Details','Registration','Positions','Check-In','Branding','Review'];

export function OpportunityEditor(){
 const {organization,profile}=useWorkspace();const {eventId}=useParams();const editing=Boolean(eventId);const nav=useNavigate();
 const draftKey=`volunteer-opportunity-draft:${organization.id}:${eventId||'new'}`;const saved=(()=>{try{return JSON.parse(localStorage.getItem(draftKey)||'null')}catch{return null}})();
 const [form,setForm]=useState<Form>({...blank,...(saved?.form||{}),days:saved?.form?.days||[]}),[step,setStep]=useState(saved?.step||0),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const set=<K extends keyof Form>(key:K,value:Form[K])=>setForm(old=>({...old,[key]:value}));
 useEffect(()=>{localStorage.setItem(draftKey,JSON.stringify({form,step,savedAt:new Date().toISOString()}))},[draftKey,form,step]);
 useEffect(()=>{if(!eventId||saved)return;Promise.all([supabase!.from('events').select('*').eq('id',eventId).eq('organization_id',organization.id).single(),supabase!.from('event_occurrences').select('*').eq('event_id',eventId).order('starts_at')]).then(([eventResult,daysResult])=>{if(eventResult.error){setError(eventResult.error.message);return}const e=eventResult.data;setForm({name:e.name,description:e.description||'',type:e.opportunity_type,date:e.date,endDate:e.end_date||'',startTime:e.start_time.slice(0,5),endTime:e.end_time.slice(0,5),location:e.location,term:e.program_term||'',availability:e.availability_mode,logoUrl:e.logo_url||'',primaryColor:e.primary_color||'#163a5f',secondaryColor:e.secondary_color||'#ef7b45',days:(daysResult.data||[]).map(d=>({date:d.starts_at.slice(0,10),startTime:new Date(d.starts_at).toLocaleTimeString('en-US',{hour12:false,hour:'2-digit',minute:'2-digit'}),endTime:new Date(d.ends_at).toLocaleTimeString('en-US',{hour12:false,hour:'2-digit',minute:'2-digit'}),location:d.location||''}))})})},[eventId,organization.id]);
 const addDay=()=>set('days',[...form.days,{date:'',startTime:'08:00',endTime:'13:00',location:''}]);
 const updateDay=(index:number,key:keyof Day,value:string)=>set('days',form.days.map((day,i)=>i===index?{...day,[key]:value}:day));
 const removeDay=(index:number)=>set('days',form.days.filter((_,i)=>i!==index));
 const chooseLogo=async(file?:File)=>{if(!file)return;setBusy(true);setError('');try{const palette=await extractBrandPalette(file);const path=`${organization.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const {error}=await supabase!.storage.from('event-logos').upload(path,file,{upsert:false});if(error)throw error;const {data}=supabase!.storage.from('event-logos').getPublicUrl(path);setForm(old=>({...old,logoUrl:data.publicUrl,primaryColor:palette.primary,secondaryColor:palette.secondary}))}catch(e){setError(e instanceof Error?e.message:'Logo analysis failed')}finally{setBusy(false)}};
 const publish=async()=>{const days=form.type==='multi_day'?form.days:[];if(!form.name||!form.date||!form.location){setError('Name, start date, and primary location are required.');setStep(0);return}if(form.type==='multi_day'&&(!form.endDate||days.length===0||days.some(d=>!d.date||!d.location))){setError('Add every event day and its location.');setStep(0);return}setBusy(true);setError('');const slug=form.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+crypto.randomUUID().slice(0,6);const payload={organization_id:organization.id,created_by:profile.id,name:form.name,slug,description:form.description||null,opportunity_type:form.type,date:form.date,end_date:form.type==='one_time'?null:form.endDate,start_time:form.startTime,end_time:form.endTime,timezone:'America/New_York',location:form.location,visibility:'public',status:'published',attendance_mode:form.type==='ongoing_program'?'program_signin':'event_checkin',availability_mode:availabilityMode(form.type,form.availability),program_term:form.type==='ongoing_program'?form.term:null,logo_url:form.logoUrl||null,primary_color:form.primaryColor,secondary_color:form.secondaryColor};const query=editing?supabase!.from('events').update(payload).eq('id',eventId!):supabase!.from('events').insert(payload);const {data,error}=await query.select('id').single();if(error){setError(error.message);setBusy(false);return}if(editing)await supabase!.from('event_occurrences').delete().eq('event_id',data.id);if(days.length){const {error:daysError}=await supabase!.from('event_occurrences').insert(days.map(day=>({organization_id:organization.id,event_id:data.id,starts_at:`${day.date}T${day.startTime}:00-04:00`,ends_at:`${day.date}T${day.endTime}:00-04:00`,location:day.location})));if(daysError){setError(daysError.message);setBusy(false);return}}if(!editing)await supabase!.from('event_registration_fields').insert(['first_name','last_name','email','phone','school_organization'].map((field,i)=>({event_id:data.id,field_key:field,label:field.replaceAll('_',' '),field_type:i===2?'email':i===3?'phone':'text',required:i<3,sort_order:i})));localStorage.removeItem(draftKey);nav('/app/events')};
 return <div className="wizard"><div className="wizard-top"><button className="back" onClick={()=>nav('/app/events')}><ChevronLeft/>Opportunities</button><div><h1>{editing?'Edit opportunity':'Create a live opportunity'}</h1><span className="autosave"><Check/>Draft saved automatically</span></div></div><ol className="steps">{steps.map((s,i)=><li className={i===step?'active':i<step?'done':''} key={s}><span>{i<step?<Check/>:i+1}</span><b>{s}</b></li>)}</ol><section className="panel form-card">{error&&<div className="error">{error}</div>}{step===0?<Details form={form} set={set} addDay={addDay} updateDay={updateDay} removeDay={removeDay}/>:step===4?<Branding form={form} chooseLogo={chooseLogo} set={set} busy={busy}/>:step===5?<Review form={form}/>:<SimpleStep step={step} type={form.type}/>}<div className="form-actions"><button className="button" disabled={step===0||busy} onClick={()=>setStep((s:number)=>s-1)}>Back</button>{step<5?<button className="button primary" onClick={()=>setStep((s:number)=>s+1)}>Continue <ChevronRight/></button>:<button disabled={busy} className="button primary" onClick={publish}>{busy?'Saving…':editing?'Save changes':'Publish opportunity'} <ArrowUpRight/></button>}</div></section></div>
}

function Details({form,set,addDay,updateDay,removeDay}:{form:Form;set:<K extends keyof Form>(k:K,v:Form[K])=>void;addDay:()=>void;updateDay:(i:number,k:keyof Day,v:string)=>void;removeDay:(i:number)=>void}){const choices:[OpportunityType,string,string][]=[['one_time','One-time event','STEM Day, conference, competition'],['multi_day','Multi-day event','Several days, schedules, and locations'],['ongoing_program','Ongoing program','Semester volunteers, tutoring, office support']];return <><span className="eyebrow">STEP 1 OF 6</span><h2>What are you organizing?</h2><div className="opportunity-types">{choices.map(([id,title,description])=><button type="button" key={id} className={form.type===id?'selected':''} onClick={()=>set('type',id)}>{id==='ongoing_program'?<Repeat2/>:<CalendarDays/>}<span><b>{title}</b><small>{description}</small></span>{form.type===id&&<Check className="choice-check"/>}</button>)}</div><div className="form-grid"><label className="full">Opportunity name *<input value={form.name} onChange={e=>set('name',e.target.value)}/></label><label className="full">Description<textarea rows={4} value={form.description} onChange={e=>set('description',e.target.value)}/></label><label>Start date *<input type="date" value={form.date} onChange={e=>set('date',e.target.value)}/></label>{form.type!=='one_time'&&<label>End date *<input type="date" value={form.endDate} onChange={e=>set('endDate',e.target.value)}/></label>}<label>Default start time<input type="time" value={form.startTime} onChange={e=>set('startTime',e.target.value)}/></label><label>Default end time<input type="time" value={form.endTime} onChange={e=>set('endTime',e.target.value)}/></label><label className="full">Primary location *<input value={form.location} onChange={e=>set('location',e.target.value)}/></label></div>{form.type==='multi_day'&&<div className="schedule-days"><div className="section-head"><div><h2>Event days and locations</h2><p>Volunteers will choose one or more of these days during registration.</p></div><button className="button" type="button" onClick={addDay}><Plus/>Add day</button></div>{form.days.map((day,i)=><div className="schedule-day" key={i}><b>Day {i+1}</b><input aria-label={`Day ${i+1} date`} type="date" value={day.date} onChange={e=>updateDay(i,'date',e.target.value)}/><input aria-label={`Day ${i+1} start time`} type="time" value={day.startTime} onChange={e=>updateDay(i,'startTime',e.target.value)}/><input aria-label={`Day ${i+1} end time`} type="time" value={day.endTime} onChange={e=>updateDay(i,'endTime',e.target.value)}/><input aria-label={`Day ${i+1} location`} placeholder="Location" value={day.location} onChange={e=>updateDay(i,'location',e.target.value)}/><button className="icon" type="button" onClick={()=>removeDay(i)}><Trash2/></button></div>)}{!form.days.length&&<button className="button" type="button" onClick={addDay}><Plus/>Add the first event day</button>}</div>}</>}
function Branding({form,chooseLogo,set,busy}:{form:Form;chooseLogo:(f?:File)=>void;set:<K extends keyof Form>(k:K,v:Form[K])=>void;busy:boolean}){return <><span className="eyebrow">STEP 5 OF 6</span><h2>Event branding</h2><p>Upload an optional logo. The app automatically analyzes its dominant colors and creates an event-specific sign-in theme.</p><div className="brand-designer" style={{'--event-primary':form.primaryColor,'--event-accent':form.secondaryColor} as React.CSSProperties}><div className="brand-preview">{form.logoUrl?<img src={form.logoUrl} alt="Event logo preview"/>:<div className="brand-placeholder">Your logo</div>}<h3>{form.name||'Event name'}</h3><button className="button primary">Sign in</button></div><div><label className="button"><Upload/> {busy?'Analyzing…':'Upload event logo'}<input hidden type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={e=>chooseLogo(e.target.files?.[0])}/></label><div className="palette"><label>Primary color<input type="color" value={form.primaryColor} onChange={e=>set('primaryColor',e.target.value)}/></label><label>Accent color<input type="color" value={form.secondaryColor} onChange={e=>set('secondaryColor',e.target.value)}/></label></div><small>You can adjust the detected colors before publishing.</small></div></div></>}
function SimpleStep({step,type}:{step:number;type:OpportunityType}){return <><span className="eyebrow">STEP {step+1} OF 6</span><h2>{steps[step]}</h2><div className="program-callout"><Check/><div><b>{step===1&&type==='multi_day'?'Day selection enabled':'Configured'}</b><span>{step===1&&type==='multi_day'?'Volunteers must choose at least one scheduled day.':'You can refine these settings after publishing.'}</span></div></div></>}
function Review({form}:{form:Form}){return <><span className="eyebrow">STEP 6 OF 6</span><h2>Ready to publish?</h2><div className="review-box"><div><Check/><span><b>{form.name||'Untitled opportunity'}</b><small>{opportunityLabel(form.type)} · {form.location}</small></span></div>{form.type==='multi_day'&&<div><Check/><span><b>{form.days.length} selectable days</b><small>{[...new Set(form.days.map(d=>d.location))].length} locations</small></span></div>}<div><Check/><span><b>Event branding</b><small>{form.logoUrl?'Custom logo and detected palette':'Default Volunteer App colors'}</small></span></div></div></>}
