import {useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {ArrowUpRight,CalendarDays,Check,ChevronLeft,Clock,MapPin,ShieldCheck} from 'lucide-react';
import QRCode from 'qrcode';
import {Copyright,Status} from '../components/UI';
import {supabase} from '../lib/supabase';
type PublicEvent={id:string;name:string;slug:string;description:string|null;date:string;end_date:string|null;start_time:string;end_time:string;location:string;capacity:number|null;status:string};
function useEvent(){const {publicSlug}=useParams();const [event,setEvent]=useState<PublicEvent|null>(null),[loading,setLoading]=useState(true);useEffect(()=>{supabase!.from('events').select('id,name,slug,description,date,end_date,start_time,end_time,location,capacity,status').eq('slug',publicSlug!).eq('visibility','public').eq('status','published').maybeSingle().then(({data})=>{setEvent(data as PublicEvent|null);setLoading(false)})},[publicSlug]);return {event,loading,publicSlug}}
const date=(d:string)=>new Date(`${d}T12:00:00`).toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'});
export function LivePublicOpportunity(){const {event:e,loading}=useEvent();if(loading)return <div className="public"><main className="panel">Loading opportunity…</main></div>;if(!e)return <div className="public"><main className="panel"><h1>Opportunity not found</h1><p>This registration page may be closed or unavailable.</p></main></div>;return <div className="public"><header><div className="customer-brand"><span className="org-avatar large">VA</span><div><b>Volunteer App</b><small>Volunteer Programs</small></div></div><Link className="button" to={`/event/${e.slug}/register`}>Register</Link></header><div className="hero"><div className="hero-copy"><Status value={e.status}/><span className="eyebrow">VOLUNTEER OPPORTUNITY</span><h1>{e.name}</h1><p>{e.description||'Join us and make a meaningful contribution.'}</p><div className="hero-details"><div><CalendarDays/><span><b>{date(e.date)}</b>{e.start_time.slice(0,5)} – {e.end_time.slice(0,5)}</span></div><div><MapPin/><span><b>{e.location}</b></span></div></div><div className="hero-actions"><Link className="button primary large" to={`/event/${e.slug}/register`}>Register to volunteer <ArrowUpRight/></Link></div></div><aside className="event-summary"><span>REGISTRATION</span><h3>Volunteer with us</h3><p>Your registration is securely saved and your personal QR credential is created instantly.</p>{e.capacity&&<><hr/><b>{e.capacity} volunteer spots available</b></>}</aside></div><Copyright powered/></div>}
export function LiveRegistration(){const {event:e,loading,publicSlug}=useEvent();const [busy,setBusy]=useState(false),[error,setError]=useState(''),[confirmation,setConfirmation]=useState<{token:string;name:string}|null>(null);const submit=async(ev:React.FormEvent<HTMLFormElement>)=>{ev.preventDefault();setBusy(true);setError('');const fd=new FormData(ev.currentTarget);const {data,error}=await supabase!.rpc('register_for_event',{event_slug:publicSlug,first_name:String(fd.get('firstName')),last_name:String(fd.get('lastName')),email:String(fd.get('email')),phone:String(fd.get('phone'))||null,school:String(fd.get('school'))||null,requested_position:null});setBusy(false);if(error)setError(error.message);else setConfirmation({token:(data as any).secure_token,name:String(fd.get('firstName'))})};if(confirmation&&e)return <Confirmation event={e} {...confirmation}/>;if(loading)return <div className="public"><main className="panel">Loading registration…</main></div>;if(!e)return <div className="public"><main className="panel"><h1>Registration unavailable</h1></main></div>;return <div className="public registration"><header><div className="customer-brand"><span className="org-avatar">VA</span><div><b>Volunteer App</b><small>Live volunteer registration</small></div></div><Link to={`/event/${publicSlug}`} className="back"><ChevronLeft/>Opportunity details</Link></header><div className="registration-layout"><aside><span className="eyebrow">YOU’RE REGISTERING FOR</span><h2>{e.name}</h2><p><CalendarDays/> {date(e.date)}</p><p><Clock/> {e.start_time.slice(0,5)} – {e.end_time.slice(0,5)}</p><p><MapPin/> {e.location}</p><div className="privacy"><ShieldCheck/><span><b>Your information is protected</b>Only authorized staff can access your registration.</span></div></aside><form className="panel" onSubmit={submit}>{error&&<div className="error">{error}</div>}<span className="eyebrow">VOLUNTEER INFORMATION</span><h1>Let’s get you registered</h1><div className="form-grid"><label>First name *<input name="firstName" required autoComplete="given-name"/></label><label>Last name *<input name="lastName" required autoComplete="family-name"/></label><label className="full">Email address *<input name="email" required type="email" autoComplete="email"/></label><label>Phone number<input name="phone" type="tel"/></label><label>School / organization<input name="school"/></label></div><label className="consent"><input required type="checkbox"/><span>I agree to the participation guidelines. *</span></label><button disabled={busy} className="button primary submit">{busy?'Submitting…':'Complete registration'}<ArrowUpRight/></button></form></div><Copyright powered/></div>}
function Confirmation({event:e,token,name}:{event:PublicEvent;token:string;name:string}){const [qr,setQr]=useState('');useEffect(()=>{QRCode.toDataURL(token,{width:320,margin:2}).then(setQr)},[token]);return <div className="confirmation public"><main><div className="success-mark"><Check/></div><span className="eyebrow">REGISTRATION CONFIRMED</span><h1>You’re all set, {name}!</h1><p>Your registration is now saved in the live volunteer database.</p><div className="credential panel"><div className="credential-info"><span>VOLUNTEER CREDENTIAL</span><h2>{e.name}</h2><div><CalendarDays/>{date(e.date)}</div><div><MapPin/>{e.location}</div><hr/><label>Volunteer<b>{name}</b></label></div><div className="qr">{qr&&<img src={qr} alt="Secure attendance QR code"/>}<b>Present at sign-in</b><small>This secure code is unique to your registration.</small></div></div><div className="notice"><ShieldCheck/><div><b>Keep this QR private</b><span>It identifies your registration but contains no personal information.</span></div></div></main><Copyright powered/></div>}
