create extension if not exists pgcrypto;
create schema if not exists private;

create type public.platform_role as enum ('user','platform_admin');
create type public.member_role as enum ('owner','administrator','event_coordinator','check_in_staff');
create type public.event_status as enum ('draft','published','registration_closed','in_progress','attendance_review','finalized','archived','cancelled');
create type public.registration_status as enum ('registered','waitlisted','cancelled');
create type public.registration_source as enum ('public_registration','walk_in','admin_added');

create table public.profiles (id uuid primary key default gen_random_uuid(),auth_user_id uuid unique not null references auth.users(id) on delete cascade,first_name text not null,last_name text not null,email text not null,phone text,platform_role public.platform_role not null default 'user',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.organizations (id uuid primary key default gen_random_uuid(),name text not null,slug text unique not null,logo_path text,accent_color text not null default '#ef7b45',contact_email text,status text not null default 'active' check(status in('active','suspended','archived')),billing_customer_id text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.organization_members (organization_id uuid not null references public.organizations(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,role public.member_role not null,status text not null default 'active' check(status in('invited','active','disabled')),created_at timestamptz not null default now(),primary key(organization_id,user_id));
create table public.events (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,slug text not null,description text,date date not null,start_time time not null,end_time time not null,timezone text not null default 'America/New_York',location text,coordinator_id uuid references public.profiles(id),contact_email text,registration_opens_at timestamptz,registration_closes_at timestamptz,capacity integer check(capacity is null or capacity>0),visibility text not null default 'public' check(visibility in('public','private')),allow_walk_ins boolean not null default true,enable_kiosk boolean not null default true,require_checkout boolean not null default true,credit_method text not null default 'actual',certificate_enabled boolean not null default true,letter_enabled boolean not null default true,status public.event_status not null default 'draft',created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,slug));
create table public.event_registration_fields (id uuid primary key default gen_random_uuid(),event_id uuid not null references public.events(id) on delete cascade,field_key text not null,label text not null,type text not null,required boolean not null default false,enabled boolean not null default true,sort_order integer not null default 0,unique(event_id,field_key));
create table public.volunteer_positions (id uuid primary key default gen_random_uuid(),event_id uuid not null references public.events(id) on delete cascade,name text not null,description text,capacity integer,start_time time,end_time time,minimum_age integer,minimum_grade integer,instructions text,active boolean not null default true);
create table public.volunteers (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,first_name text not null,last_name text not null,email text not null,phone text,school_organization text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,email));
create table public.registrations (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,event_id uuid not null references public.events(id) on delete cascade,volunteer_id uuid not null references public.volunteers(id),position_id uuid references public.volunteer_positions(id) on delete set null,status public.registration_status not null default 'registered',source public.registration_source not null default 'public_registration',qr_token_hash text not null unique,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(event_id,volunteer_id));
create table public.registration_responses (id uuid primary key default gen_random_uuid(),registration_id uuid not null references public.registrations(id) on delete cascade,field_id uuid not null references public.event_registration_fields(id) on delete cascade,response_value jsonb not null,unique(registration_id,field_id));
create table public.attendance_sessions (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,event_id uuid not null references public.events(id) on delete cascade,registration_id uuid not null references public.registrations(id) on delete cascade,checked_in_at timestamptz not null,checked_out_at timestamptz,check_in_method text not null,check_out_method text,checked_in_by uuid references public.profiles(id),checked_out_by uuid references public.profiles(id),recorded_minutes integer generated always as (case when checked_out_at is null then null else greatest(0,floor(extract(epoch from (checked_out_at-checked_in_at))/60))::integer end) stored,status text not null default 'open',check(checked_out_at is null or checked_out_at>=checked_in_at));
create table public.scan_events (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,event_id uuid not null references public.events(id) on delete cascade,registration_id uuid references public.registrations(id) on delete set null,scanned_at timestamptz not null default now(),result text not null check(result in('checkin','checkout','duplicate_ignored','invalid','blocked')),device_session text,raw_token_fingerprint text);
create table public.service_awards (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,event_id uuid not null references public.events(id) on delete cascade,registration_id uuid not null references public.registrations(id) on delete cascade,recorded_minutes integer not null default 0,adjustment_minutes integer not null default 0,awarded_minutes integer not null default 0,reason text,note text,status text not null default 'draft' check(status in('draft','finalized')),approved_by uuid references public.profiles(id),approved_at timestamptz,updated_at timestamptz not null default now(),unique(registration_id),check(awarded_minutes>=0));
create table public.document_templates (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,type text not null check(type in('certificate','verification_letter')),name text not null,content text not null,logo_path text,signature_path text,authorized_person text,authorized_title text,active boolean not null default true);
create table public.documents (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,event_id uuid not null references public.events(id) on delete cascade,registration_id uuid not null references public.registrations(id) on delete cascade,type text not null check(type in('certificate','verification_letter')),storage_path text not null,generated_by uuid references public.profiles(id),generated_at timestamptz not null default now(),emailed_at timestamptz,status text not null default 'generated',version integer not null default 1,is_current boolean not null default true,unique(registration_id,type,version));
create table public.communications (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,event_id uuid references public.events(id) on delete cascade,registration_id uuid references public.registrations(id) on delete set null,type text not null,recipient text not null,subject text not null,status text not null check(status in('queued','sent','failed')),sent_at timestamptz,error text,created_at timestamptz not null default now());
create table public.audit_logs (id bigint generated always as identity primary key,organization_id uuid not null references public.organizations(id) on delete cascade,event_id uuid references public.events(id) on delete cascade,actor_id uuid references public.profiles(id),action text not null,entity_type text not null,entity_id uuid,previous_values jsonb,new_values jsonb,reason text,created_at timestamptz not null default now());

create index on public.events(organization_id,status,date); create index on public.events(coordinator_id); create index on public.events(created_by);
create index on public.organization_members(user_id);
create index on public.event_registration_fields(event_id); create index on public.volunteer_positions(event_id);
create index on public.registrations(organization_id,event_id,status); create index on public.registrations(volunteer_id); create index on public.registrations(position_id);
create index on public.registration_responses(field_id);
create index on public.volunteers(organization_id,lower(last_name),lower(first_name));
create index on public.attendance_sessions(event_id,registration_id); create index on public.attendance_sessions(organization_id); create index on public.attendance_sessions(registration_id); create index on public.attendance_sessions(checked_in_by); create index on public.attendance_sessions(checked_out_by);
create index on public.scan_events(event_id,scanned_at desc); create index on public.scan_events(organization_id); create index on public.scan_events(registration_id);
create index on public.service_awards(event_id,status); create index on public.service_awards(organization_id); create index on public.service_awards(approved_by);
create index on public.document_templates(organization_id); create index on public.documents(event_id,type,status); create index on public.documents(organization_id); create index on public.documents(generated_by);
create index on public.communications(organization_id); create index on public.communications(event_id); create index on public.communications(registration_id);
create index on public.audit_logs(organization_id,created_at desc); create index on public.audit_logs(event_id); create index on public.audit_logs(actor_id);

create function private.current_profile_id() returns uuid language sql stable security definer set search_path='' as $$select id from public.profiles where auth_user_id=(select auth.uid())$$;
create function private.is_platform_admin() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles where auth_user_id=(select auth.uid()) and platform_role='platform_admin')$$;
create function private.has_org_role(org uuid,roles public.member_role[] default null) returns boolean language sql stable security definer set search_path='' as $$select private.is_platform_admin() or exists(select 1 from public.organization_members m join public.profiles p on p.id=m.user_id where p.auth_user_id=(select auth.uid()) and m.organization_id=org and m.status='active' and (roles is null or m.role=any(roles)))$$;
revoke all on all functions in schema private from public,anon,authenticated; grant usage on schema private to authenticated; grant execute on function private.current_profile_id(),private.is_platform_admin(),private.has_org_role(uuid,public.member_role[]) to authenticated;

alter table public.profiles enable row level security; alter table public.organizations enable row level security; alter table public.organization_members enable row level security; alter table public.events enable row level security; alter table public.event_registration_fields enable row level security; alter table public.volunteer_positions enable row level security; alter table public.volunteers enable row level security; alter table public.registrations enable row level security; alter table public.registration_responses enable row level security; alter table public.attendance_sessions enable row level security; alter table public.scan_events enable row level security; alter table public.service_awards enable row level security; alter table public.document_templates enable row level security; alter table public.documents enable row level security; alter table public.communications enable row level security; alter table public.audit_logs enable row level security;

create policy profiles_self_or_platform on public.profiles for select to authenticated using(auth_user_id=(select auth.uid()) or private.is_platform_admin());
create policy organizations_members on public.organizations for select to authenticated using(private.has_org_role(id,null));
create policy organizations_admin_update on public.organizations for update to authenticated using(private.has_org_role(id,array['owner','administrator']::public.member_role[])) with check(private.has_org_role(id,array['owner','administrator']::public.member_role[]));
create policy members_read on public.organization_members for select to authenticated using(private.has_org_role(organization_id,null));
create policy members_owner_insert on public.organization_members for insert to authenticated with check(private.has_org_role(organization_id,array['owner','administrator']::public.member_role[]));
create policy members_owner_update on public.organization_members for update to authenticated using(private.has_org_role(organization_id,array['owner','administrator']::public.member_role[])) with check(private.has_org_role(organization_id,array['owner','administrator']::public.member_role[]));
create policy members_owner_delete on public.organization_members for delete to authenticated using(private.has_org_role(organization_id,array['owner','administrator']::public.member_role[]));
create policy events_public_read on public.events for select to anon using(visibility='public' and status in('published','registration_closed','in_progress','cancelled'));
create policy events_member_read on public.events for select to authenticated using(private.has_org_role(organization_id,null));
create policy events_admin_insert on public.events for insert to authenticated with check(private.has_org_role(organization_id,array['owner','administrator','event_coordinator']::public.member_role[]));
create policy events_admin_update on public.events for update to authenticated using(private.has_org_role(organization_id,array['owner','administrator','event_coordinator']::public.member_role[])) with check(private.has_org_role(organization_id,array['owner','administrator','event_coordinator']::public.member_role[]));
create policy events_admin_delete on public.events for delete to authenticated using(private.has_org_role(organization_id,array['owner','administrator','event_coordinator']::public.member_role[]));

do $$ declare t text; begin foreach t in array array['event_registration_fields','volunteer_positions'] loop execute format('create policy %I_public_read on public.%I for select to anon using(exists(select 1 from public.events e where e.id=event_id and e.visibility=''public'' and e.status in(''published'',''registration_closed'',''in_progress'')))',t,t); execute format('create policy %I_member_all on public.%I for all to authenticated using(exists(select 1 from public.events e where e.id=event_id and private.has_org_role(e.organization_id,null))) with check(exists(select 1 from public.events e where e.id=event_id and private.has_org_role(e.organization_id,null)))',t,t); end loop; end $$;
do $$ declare t text; begin foreach t in array array['volunteers','registrations','attendance_sessions','scan_events','service_awards','document_templates','documents','communications'] loop execute format('create policy %I_member_select on public.%I for select to authenticated using(private.has_org_role(organization_id,null))',t,t); execute format('create policy %I_member_insert on public.%I for insert to authenticated with check(private.has_org_role(organization_id,null))',t,t); execute format('create policy %I_member_update on public.%I for update to authenticated using(private.has_org_role(organization_id,null)) with check(private.has_org_role(organization_id,null))',t,t); end loop; end $$;
create policy responses_member_all on public.registration_responses for all to authenticated using(exists(select 1 from public.registrations r where r.id=registration_id and private.has_org_role(r.organization_id,null))) with check(exists(select 1 from public.registrations r where r.id=registration_id and private.has_org_role(r.organization_id,null)));
create policy audit_read on public.audit_logs for select to authenticated using(private.has_org_role(organization_id,array['owner','administrator','event_coordinator']::public.member_role[]));
create policy audit_insert on public.audit_logs for insert to authenticated with check(private.has_org_role(organization_id,null) and actor_id=private.current_profile_id());

revoke all on all tables in schema public from anon,authenticated; grant select on public.events,public.event_registration_fields,public.volunteer_positions to anon; grant select,insert,update on all tables in schema public to authenticated; grant usage,select on all sequences in schema public to authenticated;

create function private.register_for_event_impl(event_slug text,first_name text,last_name text,email text,phone text default null,school text default null,requested_position uuid default null) returns table(registration_id uuid,secure_token text) language plpgsql security definer set search_path='' as $$declare ev public.events;vol uuid;token text;reg uuid;begin select * into ev from public.events where slug=event_slug and visibility='public' and status='published' and (registration_opens_at is null or registration_opens_at<=now()) and (registration_closes_at is null or registration_closes_at>=now()) for update;if ev.id is null then raise exception 'Registration is not available';end if;if ev.capacity is not null and (select count(*) from public.registrations where event_id=ev.id and status='registered')>=ev.capacity then raise exception 'Registration is full';end if;select id into vol from public.volunteers where organization_id=ev.organization_id and lower(public.volunteers.email)=lower(register_for_event_impl.email);if vol is null then insert into public.volunteers(organization_id,first_name,last_name,email,phone,school_organization) values(ev.organization_id,trim(first_name),trim(last_name),lower(trim(email)),phone,school) returning id into vol;end if;if exists(select 1 from public.registrations where event_id=ev.id and volunteer_id=vol and status<>'cancelled') then raise exception 'Already registered';end if;token:=encode(gen_random_bytes(32),'base64');insert into public.registrations(organization_id,event_id,volunteer_id,position_id,qr_token_hash) values(ev.organization_id,ev.id,vol,requested_position,encode(digest(token,'sha256'),'hex')) returning id into reg;return query select reg,token;end$$;
revoke all on function private.register_for_event_impl(text,text,text,text,text,text,uuid) from public,anon,authenticated;
create function public.register_for_event(event_slug text,first_name text,last_name text,email text,phone text default null,school text default null,requested_position uuid default null) returns table(registration_id uuid,secure_token text) language sql security invoker set search_path='' as $$select * from private.register_for_event_impl(event_slug,first_name,last_name,email,phone,school,requested_position)$$;
revoke all on function public.register_for_event(text,text,text,text,text,text,uuid) from public; grant execute on function public.register_for_event(text,text,text,text,text,text,uuid) to anon,authenticated; grant execute on function private.register_for_event_impl(text,text,text,text,text,text,uuid) to anon,authenticated;

create function private.prevent_audit_changes() returns trigger language plpgsql set search_path='' as $$begin raise exception 'Audit logs are append-only';end$$;
create trigger audit_logs_append_only before update or delete on public.audit_logs for each row execute function private.prevent_audit_changes();
